Repository Witty-Wizard/SerialIO, pull requests merged in 2024-12, with the labels that each got.

#30 Fixed Bug, Channel 1 was being mixed with the header byte
  src/ibus/ibus.cpp
Labels: bugfixes 🐞

#32 Added: method for returning 16 bit channels
  src/SerialIO.cpp
  src/SerialIO.h
  src/ibus/ibus.cpp
  src/ibus/ibus.h
Labels: enhancement 🪄

#31 Create example for ibus on RP2040
  examples/rp2040/ibus_basic/.arduino-ci.yml
  examples/rp2040/ibus_basic/ibus_basic.ino
Labels: documentation 📖

#34 33 feature use loops in ibus getchannels goddammit
  src/ibus/ibus.cpp
Labels: enhancement 🪄
